apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  goconsumer
  labels:
    name:  goconsumer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  goconsumer
    spec:
      containers:
      - image:  gointensivo
        name:  goconsumer
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  8080
          name:  goconsumer
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always